apiVersion: v1
kind: Pod # resource kind
metadata:
  name: hello-world
spec:
  containers:
  - name: hello-world-container
    image: imagename
    args: ["echo","hello"]
    imagePullPolicy: IfNotPresent # Imported from local machine.
    ports:
    - containerPort: PORT  # Container port.
