apiVersion: v1
kind: Pod
metadata:
  name: busybox-demo
  labels:
   app: busybox-demo
spec:
  containers:
  - image: busybox
    command: ["sh", "-c"]
    args: ["echo Hello!; sleep 3600"]
    name: busybox